site_name: ben_py_utils

nav:
  - Home: index.md
  - Documentation: 
    - Misc:
      - SSL: ssl.md
      - Cache: cache.md
      - Profiler: profiler.md
      - Compose: compose.md

docs_dir:
  site_build

site_dir:
  docs

use_directory_urls:
  false

plugins:
  - search
  - mkdocstrings

theme:
  name: readthedocs