site_name: ben_py_utils

nav:
  - Home: index.md
  - Documentation: references.md

docs_dir:
  site_build

site_dir:
  docs

use_directory_urls:
  false

plugins:
  - search
  - mkdocstrings

theme:
  name: readthedocs