[tool.poetry]
name = "ben_py_utils"
version = "0.1.0"
description = ""
authors = ["Charles Gauvin"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.9"
brotlipy = "*"
folium = "*"
gendocs = "*"
mapclassify = "*"
matplotlib = "*"
munkres = "*"
myst-nb = "*"
pathlib = "*"
pyarrow = "*"
pyopenssl = "*"
pysocks = "*"
typing = "*"
unicodedata2 = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
